-- Add series column to programs table
ALTER TABLE programs ADD COLUMN IF NOT EXISTS series TEXT;

-- Insert all music page programs with series classification
-- Existing programs (matched by program_name) get their series updated while keeping color data
INSERT INTO programs (program_name, series) VALUES
  ('BB1 10''s 1', 'BB1'),
  ('BB1 10''s 2', 'BB1'),
  ('BB1 90''s 1', 'BB1'),
  ('BB1 BRIT 2024', 'BB1'),
  ('BB1 COMP 1', 'BB1'),
  ('BB1 COMP 2', 'BB1'),
  ('BB1 COMP 3', 'BB1'),
  ('BB1 COMP 4', 'BB1'),
  ('BB1 DVGT', 'BB1'),
  ('BB1 GRMY 65', 'BB1'),
  ('BB1 GRMY 67', 'BB1'),
  ('BB1 HIT 1', 'BB1'),
  ('BB1 HIT 10', 'BB1'),
  ('BB1 HIT 11', 'BB1'),
  ('BB1 HIT 2', 'BB1'),
  ('BB1 HIT 3', 'BB1'),
  ('BB1 HIT 4', 'BB1'),
  ('BB1 HIT 5', 'BB1'),
  ('BB1 HIT 6', 'BB1'),
  ('BB1 HIT 7', 'BB1'),
  ('BB1 HIT 8', 'BB1'),
  ('BB1 HIT 9', 'BB1'),
  ('BB1 HOUSE 1', 'BB1'),
  ('BB1 HOUSE 2', 'BB1'),
  ('BB1 HOUSE 3', 'BB1'),
  ('BB1 HOUSE 4', 'BB1'),
  ('BB1 HOUSE 5', 'BB1'),
  ('BB1 NOW 1', 'BB1'),
  ('BB1 NOW 2', 'BB1'),
  ('BB1 QUEEN', 'BB1'),
  ('BB1 TSFT', 'BB1'),
  ('BB2 10''s 1', 'BB2'),
  ('BB2 10''s 2', 'BB2'),
  ('BB2 10''s 3', 'BB2'),
  ('BB2 10''s 4', 'BB2'),
  ('BB2 1D', 'BB2'),
  ('BB2 2016', 'BB2'),
  ('BB2 2017', 'BB2'),
  ('BB2 2018', 'BB2'),
  ('BB2 2019', 'BB2'),
  ('BB2 3Y-1', 'BB2'),
  ('BB2 3Y-2', 'BB2'),
  ('BB2 90''s 1', 'BB2'),
  ('BB2 90''s 2', 'BB2'),
  ('BB2 ADELE', 'BB2'),
  ('BB2 ARGD', 'BB2'),
  ('BB2 AVICII', 'BB2'),
  ('BB2 BEYONCE', 'BB2'),
  ('BB2 BMLY', 'BB2'),
  ('BB2 BNJV', 'BB2'),
  ('BB2 BRIT 2023', 'BB2'),
  ('BB2 BRIT 2025', 'BB2'),
  ('BB2 BRJ', 'BB2'),
  ('BB2 BRMS', 'BB2'),
  ('BB2 BRMS 2', 'BB2'),
  ('BB2 BTLS', 'BB2'),
  ('BB2 BTLS 2', 'BB2'),
  ('BB2 BTLS 3', 'BB2'),
  ('BB2 CDPY', 'BB2'),
  ('BB2 CDPY 2', 'BB2'),
  ('BB2 CHARLI', 'BB2'),
  ('BB2 COMP 1', 'BB2'),
  ('BB2 COMP 2', 'BB2'),
  ('BB2 COMP 3', 'BB2'),
  ('BB2 COMP 4', 'BB2'),
  ('BB2 COMP 5', 'BB2'),
  ('BB2 COMP 6', 'BB2'),
  ('BB2 COMP 7', 'BB2'),
  ('BB2 COMP 8', 'BB2'),
  ('BB2 CSBW', 'BB2'),
  ('BB2 CSBW 2', 'BB2'),
  ('BB2 CVHS', 'BB2'),
  ('BB2 DEEP 1', 'BB2'),
  ('BB2 DEEP 2', 'BB2'),
  ('BB2 DEEP 3', 'BB2'),
  ('BB2 DUA LIPA', 'BB2'),
  ('BB2 DUA LIPA2', 'BB2'),
  ('BB2 DVGT', 'BB2'),
  ('BB2 EDM', 'BB2'),
  ('BB2 EDSR', 'BB2'),
  ('BB2 EMINEM', 'BB2'),
  ('BB2 FLG', 'BB2'),
  ('BB2 FOB', 'BB2'),
  ('BB2 GRDY', 'BB2'),
  ('BB2 GRMY 66', 'BB2'),
  ('BB2 HIPHOP 1', 'BB2'),
  ('BB2 HIPHOP 2', 'BB2'),
  ('BB2 HIT 1', 'BB2'),
  ('BB2 HIT 10', 'BB2'),
  ('BB2 HIT 11', 'BB2'),
  ('BB2 HIT 12', 'BB2'),
  ('BB2 HIT 13', 'BB2'),
  ('BB2 HIT 14', 'BB2'),
  ('BB2 HIT 15', 'BB2'),
  ('BB2 HIT 16', 'BB2'),
  ('BB2 HIT 17', 'BB2'),
  ('BB2 HIT 18', 'BB2'),
  ('BB2 HIT 19', 'BB2'),
  ('BB2 HIT 2', 'BB2'),
  ('BB2 HIT 20', 'BB2'),
  ('BB2 HIT 21', 'BB2'),
  ('BB2 HIT 22', 'BB2'),
  ('BB2 HIT 3', 'BB2'),
  ('BB2 HIT 4', 'BB2'),
  ('BB2 HIT 5', 'BB2'),
  ('BB2 HIT 6', 'BB2'),
  ('BB2 HIT 7', 'BB2'),
  ('BB2 HIT 8', 'BB2'),
  ('BB2 HIT 9', 'BB2'),
  ('BB2 HOUSE 1', 'BB2'),
  ('BB2 HOUSE 2', 'BB2'),
  ('BB2 HOUSE 3', 'BB2'),
  ('BB2 HOUSE 4', 'BB2'),
  ('BB2 HOUSE 5', 'BB2'),
  ('BB2 HOUSE 6', 'BB2'),
  ('BB2 HOUSE 7', 'BB2'),
  ('BB2 JAZZ 1', 'BB2'),
  ('BB2 JONAS', 'BB2'),
  ('BB2 JUSTIN', 'BB2'),
  ('BB2 KYGO', 'BB2'),
  ('BB2 LDGG', 'BB2'),
  ('BB2 LDGG 2', 'BB2'),
  ('BB2 MDNA', 'BB2'),
  ('BB2 METAL 1', 'BB2'),
  ('BB2 METAL 2', 'BB2'),
  ('BB2 MJ', 'BB2'),
  ('BB2 MJ2', 'BB2'),
  ('BB2 MJ3', 'BB2'),
  ('BB2 MLN1', 'BB2'),
  ('BB2 MLN2', 'BB2'),
  ('BB2 MLN3', 'BB2'),
  ('BB2 MOVIE 1', 'BB2'),
  ('BB2 MOVIE 2', 'BB2'),
  ('BB2 MRN5', 'BB2'),
  ('BB2 MTGX', 'BB2'),
  ('BB2 NE-YO', 'BB2'),
  ('BB2 NOW 1', 'BB2'),
  ('BB2 NOW 2', 'BB2'),
  ('BB2 NOW 3', 'BB2'),
  ('BB2 PINK', 'BB2'),
  ('BB2 PTX', 'BB2'),
  ('BB2 QOP', 'BB2'),
  ('BB2 QUEEN', 'BB2'),
  ('BB2 R&B', 'BB2'),
  ('BB2 R&B 2', 'BB2'),
  ('BB2 REGGAE 1', 'BB2'),
  ('BB2 REGGAE 2', 'BB2'),
  ('BB2 RHCP', 'BB2'),
  ('BB2 RHNA', 'BB2'),
  ('BB2 ROCK 1', 'BB2'),
  ('BB2 ROCK 2', 'BB2'),
  ('BB2 SIGALA', 'BB2'),
  ('BB2 SMST', 'BB2'),
  ('BB2 SOUL 1', 'BB2'),
  ('BB2 SOUL 2', 'BB2'),
  ('BB2 SUMMER 1', 'BB2'),
  ('BB2 SUMMER 2', 'BB2'),
  ('BB2 UPGD 1', 'BB2'),
  ('BB2 UPGD 2', 'BB2'),
  ('BB2 UPGD 3', 'BB2'),
  ('BB2 USHER', 'BB2'),
  ('BB2 USHER 2', 'BB2'),
  ('BB2 X''mas 2', 'BB2'),
  ('BB2 X''mas 3', 'BB2'),
  ('BB2 X''MAS 4', 'BB2'),
  ('BB2 ZEDD', 'BB2'),
  ('SKRILLEX', 'BB2'),
  ('BB3 10''s 1', 'BB3'),
  ('BB3 COMP 1', 'BB3'),
  ('BB3 DEEP 1', 'BB3'),
  ('BB3 HIPHOP 1', 'BB3'),
  ('BB3 HIPHOP 2', 'BB3'),
  ('BB3 HIT 1', 'BB3'),
  ('BB3 HIT 2', 'BB3'),
  ('BB3 HIT 3', 'BB3'),
  ('BB3 HIT 4', 'BB3'),
  ('BB3 HIT 5', 'BB3'),
  ('BB3 HIT 6', 'BB3'),
  ('BB3 HOUSE 1', 'BB3'),
  ('BB3 HOUSE 2', 'BB3'),
  ('BB3 HOUSE 3', 'BB3'),
  ('BB3 HOUSE 4', 'BB3'),
  ('BB3 IRMD', 'BB3'),
  ('BB3 REGGAE 1', 'BB3'),
  ('BB3 ROCK 1', 'BB3'),
  ('BB3 ROCK 2', 'BB3'),
  ('BB3 SOUL 1', 'BB3'),
  ('BB3 UPGD 1', 'BB3'),
  ('BB3 WORLD 1', 'BB3'),
  ('BSB 10''s 1', 'BSB'),
  ('BSB COMP 1', 'BSB'),
  ('BSB DEEP 1', 'BSB'),
  ('BSB EDSR', 'BSB'),
  ('BSB HIPHOP 1', 'BSB'),
  ('BSB HIPHOP 2', 'BSB'),
  ('BSB HIT 1', 'BSB'),
  ('BSB HIT 2', 'BSB'),
  ('BSB HIT 3', 'BSB'),
  ('BSB HIT 4', 'BSB'),
  ('BSB HIT 5', 'BSB'),
  ('BSB HIT 6', 'BSB'),
  ('BSB HIT 7', 'BSB'),
  ('BSB HOUSE 1', 'BSB'),
  ('BSB JAZZ 1', 'BSB'),
  ('BSB REGGAE 1', 'BSB'),
  ('BSB ROCK 1', 'BSB'),
  ('BSBi BMLY', 'BSBi'),
  ('BSBi DEEP 1', 'BSBi'),
  ('BSBi HOUSE 1', 'BSBi'),
  ('BSBi HOUSE 2', 'BSBi'),
  ('BSL COMP 1', 'BSL'),
  ('BSL DEEP 1', 'BSL'),
  ('BSL DEEP 2', 'BSL'),
  ('BSL DEEP 3', 'BSL'),
  ('BSL DEEP 4', 'BSL'),
  ('BSL HIT 1', 'BSL'),
  ('BSL HIT 2', 'BSL'),
  ('BSL HIT 3', 'BSL'),
  ('BSL HIT 4', 'BSL'),
  ('BSL HIT 5', 'BSL'),
  ('BSL HIT 6', 'BSL'),
  ('BSL HIT 7', 'BSL'),
  ('BSL HIT 8', 'BSL'),
  ('BSL HOUSE 1', 'BSL'),
  ('BSL HOUSE 2', 'BSL'),
  ('BSL R&B 1', 'BSL'),
  ('BSL ROCK 1', 'BSL'),
  ('BSW 10''s 1', 'BSW'),
  ('BSW COMP 1', 'BSW'),
  ('BSW COMP 2', 'BSW'),
  ('BSW COMP 3', 'BSW'),
  ('BSW HIT 1', 'BSW'),
  ('BSW HIT 2', 'BSW'),
  ('BSW HIT 3', 'BSW'),
  ('BSW HIT 4', 'BSW'),
  ('BSW HIT 5', 'BSW'),
  ('BSW HIT 6', 'BSW'),
  ('BSW HIT 7', 'BSW'),
  ('BSW HIT 8', 'BSW'),
  ('BSW HOUSE 1', 'BSW'),
  ('BSW HOUSE 2', 'BSW'),
  ('BSW HOUSE 3', 'BSW'),
  ('BSW JAZZ 1', 'BSW'),
  ('BSW L&S', 'BSW'),
  ('BSW MRN5', 'BSW'),
  ('BSW R&B 1', 'BSW'),
  ('BSW REGGAE 1', 'BSW'),
  ('BSW ROCK 1', 'BSW'),
  ('BSW SOUL 1', 'BSW'),
  ('BSWi BMLY', 'BSWi'),
  ('BSWi HIPHOP 1', 'BSWi'),
  ('BSWi HOUSE 1', 'BSWi'),
  ('BSWi HOUSE 2', 'BSWi'),
  ('BSWi HOUSE 3', 'BSWi'),
  ('BSWi HOUSE 4', 'BSWi'),
  ('BSWi METAL 1', 'BSWi'),
  ('10TH SP', 'OTHER'),
  ('9th SP 1', 'OTHER'),
  ('9th SP 2', 'OTHER'),
  ('BEERCYCLE', 'OTHER'),
  ('FEEL DEEP', 'OTHER'),
  ('FEEL DEEP 2', 'OTHER'),
  ('FEEL HIGH', 'OTHER'),
  ('FEEL HIGH 2', 'OTHER'),
  ('FEEL NOW B1', 'OTHER'),
  ('FEEL NOW B2', 'OTHER'),
  ('FEEL NOW B3', 'OTHER'),
  ('FEEL NOW B4', 'OTHER'),
  ('FEEL NOW G1', 'OTHER'),
  ('FEEL NOW G2', 'OTHER'),
  ('FEEL NOW G3', 'OTHER'),
  ('FEEL NOW S1', 'OTHER'),
  ('FEEL NOW S2', 'OTHER'),
  ('FEEL NOW S3', 'OTHER'),
  ('L 24 FEEL', 'OTHER'),
  ('L 24 FEEL 2', 'OTHER'),
  ('L 24 FREE', 'OTHER'),
  ('L 24 FREE 2', 'OTHER'),
  ('L 25 BTM', 'OTHER'),
  ('L 25 FEEL', 'OTHER'),
  ('L 25 FREE', 'OTHER'),
  ('LUSTER 2017 COMPILATION', 'OTHER'),
  ('LUSTER 2017 ROCK', 'OTHER'),
  ('LUSTER 2018 COMPILATION', 'OTHER'),
  ('LUSTER 2018 HOUSE', 'OTHER'),
  ('LUSTER 2019 COMP', 'OTHER'),
  ('LUSTER 2019 COMPILATION', 'OTHER'),
  ('LUSTER 2019 ROCK', 'OTHER'),
  ('LUSTER 2019 ZEDD MIX', 'OTHER'),
  ('LUSTER 2022 FEEL YOURSELF', 'OTHER'),
  ('LUSTER 2022 FREE YOURSELF', 'OTHER'),
  ('LUSTER 2024 FEEL YOURSELF', 'OTHER'),
  ('LUSTER 2024 FREE YOURSELF', 'OTHER'),
  ('LUSTER 2025 FEEL YOURSELF', 'OTHER'),
  ('LUSTER 2025 FREE YOURSELF', 'OTHER'),
  ('LUSTER HOUSE', 'OTHER')
ON CONFLICT (program_name) DO UPDATE SET series = EXCLUDED.series;
