-- Rename music page program names to FEELCYCLE API convention
-- Handles merging when scraper already created an entry with the API name
-- Skipped: BB2 UPGD 1 (API double-space bug), FEEL DEEP/2, LUSTER series (uncertain)

DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('BB1 10''s 1', 'BB1 10s 1'),
    ('BB1 10''s 2', 'BB1 10s 2'),
    ('BB1 90''s 1', 'BB1 90s 1'),
    ('BB1 COMP 1', 'BB1 Comp 1'),
    ('BB1 COMP 2', 'BB1 Comp 2'),
    ('BB1 COMP 3', 'BB1 Comp 3'),
    ('BB1 COMP 4', 'BB1 Comp 4'),
    ('BB1 HIT 1', 'BB1 Hit 1'),
    ('BB1 HIT 10', 'BB1 Hit 10'),
    ('BB1 HIT 11', 'BB1 Hit 11'),
    ('BB1 HIT 2', 'BB1 Hit 2'),
    ('BB1 HIT 3', 'BB1 Hit 3'),
    ('BB1 HIT 4', 'BB1 Hit 4'),
    ('BB1 HIT 5', 'BB1 Hit 5'),
    ('BB1 HIT 6', 'BB1 Hit 6'),
    ('BB1 HIT 7', 'BB1 Hit 7'),
    ('BB1 HIT 8', 'BB1 Hit 8'),
    ('BB1 HIT 9', 'BB1 Hit 9'),
    ('BB1 HOUSE 1', 'BB1 House 1'),
    ('BB1 HOUSE 2', 'BB1 House 2'),
    ('BB1 HOUSE 3', 'BB1 House 3'),
    ('BB1 HOUSE 4', 'BB1 House 4'),
    ('BB1 HOUSE 5', 'BB1 House 5'),
    ('BB2 10''s 1', 'BB2 10s 1'),
    ('BB2 10''s 2', 'BB2 10s 2'),
    ('BB2 10''s 3', 'BB2 10s 3'),
    ('BB2 10''s 4', 'BB2 10s 4'),
    ('BB2 3Y-1', 'BB2 3Y 1'),
    ('BB2 3Y-2', 'BB2 3Y 2'),
    ('BB2 90''s 1', 'BB2 90s 1'),
    ('BB2 90''s 2', 'BB2 90s 2'),
    ('BB2 COMP 1', 'BB2 Comp 1'),
    ('BB2 COMP 2', 'BB2 Comp 2'),
    ('BB2 COMP 3', 'BB2 Comp 3'),
    ('BB2 COMP 4', 'BB2 Comp 4'),
    ('BB2 COMP 5', 'BB2 Comp 5'),
    ('BB2 COMP 6', 'BB2 Comp 6'),
    ('BB2 COMP 7', 'BB2 Comp 7'),
    ('BB2 COMP 8', 'BB2 Comp 8'),
    ('BB2 DEEP 1', 'BB2 Deep 1'),
    ('BB2 DEEP 2', 'BB2 Deep 2'),
    ('BB2 DEEP 3', 'BB2 Deep 3'),
    ('BB2 DUA LIPA2', 'BB2 DUA LIPA 2'),
    ('BB2 HIPHOP 1', 'BB2 HipHop 1'),
    ('BB2 HIPHOP 2', 'BB2 HipHop 2'),
    ('BB2 HIT 1', 'BB2 Hit 1'),
    ('BB2 HIT 10', 'BB2 Hit 10'),
    ('BB2 HIT 11', 'BB2 Hit 11'),
    ('BB2 HIT 12', 'BB2 Hit 12'),
    ('BB2 HIT 13', 'BB2 Hit 13'),
    ('BB2 HIT 14', 'BB2 Hit 14'),
    ('BB2 HIT 15', 'BB2 Hit 15'),
    ('BB2 HIT 16', 'BB2 Hit 16'),
    ('BB2 HIT 17', 'BB2 Hit 17'),
    ('BB2 HIT 18', 'BB2 Hit 18'),
    ('BB2 HIT 19', 'BB2 Hit 19'),
    ('BB2 HIT 2', 'BB2 Hit 2'),
    ('BB2 HIT 20', 'BB2 Hit 20'),
    ('BB2 HIT 21', 'BB2 Hit 21'),
    ('BB2 HIT 22', 'BB2 Hit 22'),
    ('BB2 HIT 3', 'BB2 Hit 3'),
    ('BB2 HIT 4', 'BB2 Hit 4'),
    ('BB2 HIT 5', 'BB2 Hit 5'),
    ('BB2 HIT 6', 'BB2 Hit 6'),
    ('BB2 HIT 7', 'BB2 Hit 7'),
    ('BB2 HIT 8', 'BB2 Hit 8'),
    ('BB2 HIT 9', 'BB2 Hit 9'),
    ('BB2 HOUSE 1', 'BB2 House 1'),
    ('BB2 HOUSE 2', 'BB2 House 2'),
    ('BB2 HOUSE 3', 'BB2 House 3'),
    ('BB2 HOUSE 4', 'BB2 House 4'),
    ('BB2 HOUSE 5', 'BB2 House 5'),
    ('BB2 HOUSE 6', 'BB2 House 6'),
    ('BB2 HOUSE 7', 'BB2 House 7'),
    ('BB2 JAZZ 1', 'BB2 Jazz 1'),
    ('BB2 METAL 1', 'BB2 Metal 1'),
    ('BB2 METAL 2', 'BB2 Metal 2'),
    ('BB2 MJ2', 'BB2 MJ 2'),
    ('BB2 MJ3', 'BB2 MJ 3'),
    ('BB2 MLN1', 'BB2 MLN 1'),
    ('BB2 MLN2', 'BB2 MLN 2'),
    ('BB2 MLN3', 'BB2 MLN 3'),
    ('BB2 MOVIE 1', 'BB2 Movie 1'),
    ('BB2 MOVIE 2', 'BB2 Movie 2'),
    ('BB2 NE-YO', 'BB2 NE YO'),
    ('BB2 PINK', 'BB2 P!NK'),
    ('BB2 R&B', 'BB2 R＆B 1'),
    ('BB2 R&B 2', 'BB2 R＆B 2'),
    ('BB2 REGGAE 1', 'BB2 Reggae 1'),
    ('BB2 REGGAE 2', 'BB2 Reggae 2'),
    ('BB2 ROCK 1', 'BB2 Rock 1'),
    ('BB2 ROCK 2', 'BB2 Rock 2'),
    ('BB2 SOUL 1', 'BB2 Soul 1'),
    ('BB2 SOUL 2', 'BB2 Soul 2'),
    ('BB2 SUMMER 1', 'BB2 Summer 1'),
    ('BB2 SUMMER 2', 'BB2 Summer 2'),
    ('BB2 X''mas 2', 'BB2 Xmas 2'),
    ('BB2 X''mas 3', 'BB2 Xmas 3'),
    ('BB2 X''MAS 4', 'BB2 Xmas 4'),
    ('BB3 10''s 1', 'BB3 10s 1'),
    ('BB3 COMP 1', 'BB3 Comp 1'),
    ('BB3 DEEP 1', 'BB3 Deep 1'),
    ('BB3 HIPHOP 1', 'BB3 HipHop 1'),
    ('BB3 HIPHOP 2', 'BB3 HipHop 2'),
    ('BB3 HIT 1', 'BB3 Hit 1'),
    ('BB3 HIT 2', 'BB3 Hit 2'),
    ('BB3 HIT 3', 'BB3 Hit 3'),
    ('BB3 HIT 4', 'BB3 Hit 4'),
    ('BB3 HIT 5', 'BB3 Hit 5'),
    ('BB3 HIT 6', 'BB3 Hit 6'),
    ('BB3 HOUSE 1', 'BB3 House 1'),
    ('BB3 HOUSE 2', 'BB3 House 2'),
    ('BB3 HOUSE 3', 'BB3 House 3'),
    ('BB3 HOUSE 4', 'BB3 House 4'),
    ('BB3 REGGAE 1', 'BB3 Reggae 1'),
    ('BB3 ROCK 1', 'BB3 Rock 1'),
    ('BB3 ROCK 2', 'BB3 Rock 2'),
    ('BB3 SOUL 1', 'BB3 Soul 1'),
    ('BB3 WORLD 1', 'BB3 World 1'),
    ('BSB 10''s 1', 'BSB 10s 1'),
    ('BSB COMP 1', 'BSB Comp 1'),
    ('BSB DEEP 1', 'BSB Deep 1'),
    ('BSB HIPHOP 1', 'BSB HipHop 1'),
    ('BSB HIPHOP 2', 'BSB HipHop 2'),
    ('BSB HIT 1', 'BSB Hit 1'),
    ('BSB HIT 2', 'BSB Hit 2'),
    ('BSB HIT 3', 'BSB Hit 3'),
    ('BSB HIT 4', 'BSB Hit 4'),
    ('BSB HIT 5', 'BSB Hit 5'),
    ('BSB HIT 6', 'BSB Hit 6'),
    ('BSB HIT 7', 'BSB Hit 7'),
    ('BSB HOUSE 1', 'BSB House 1'),
    ('BSB JAZZ 1', 'BSB Jazz 1'),
    ('BSB REGGAE 1', 'BSB Reggae 1'),
    ('BSB ROCK 1', 'BSB Rock 1'),
    ('BSBi DEEP 1', 'BSBi Deep 1'),
    ('BSBi HOUSE 1', 'BSBi House 1'),
    ('BSBi HOUSE 2', 'BSBi House 2'),
    ('BSL COMP 1', 'BSL Comp 1'),
    ('BSL DEEP 1', 'BSL Deep 1'),
    ('BSL DEEP 2', 'BSL Deep 2'),
    ('BSL DEEP 3', 'BSL Deep 3'),
    ('BSL DEEP 4', 'BSL Deep 4'),
    ('BSL HIT 1', 'BSL Hit 1'),
    ('BSL HIT 2', 'BSL Hit 2'),
    ('BSL HIT 3', 'BSL Hit 3'),
    ('BSL HIT 4', 'BSL Hit 4'),
    ('BSL HIT 5', 'BSL Hit 5'),
    ('BSL HIT 6', 'BSL Hit 6'),
    ('BSL HIT 7', 'BSL Hit 7'),
    ('BSL HIT 8', 'BSL Hit 8'),
    ('BSL HOUSE 1', 'BSL House 1'),
    ('BSL HOUSE 2', 'BSL House 2'),
    ('BSL R&B 1', 'BSL R＆B 1'),
    ('BSL ROCK 1', 'BSL Rock 1'),
    ('BSW 10''s 1', 'BSW 10s 1'),
    ('BSW COMP 1', 'BSW Comp 1'),
    ('BSW COMP 2', 'BSW Comp 2'),
    ('BSW COMP 3', 'BSW Comp 3'),
    ('BSW HIT 1', 'BSW Hit 1'),
    ('BSW HIT 2', 'BSW Hit 2'),
    ('BSW HIT 3', 'BSW Hit 3'),
    ('BSW HIT 4', 'BSW Hit 4'),
    ('BSW HIT 5', 'BSW Hit 5'),
    ('BSW HIT 6', 'BSW Hit 6'),
    ('BSW HIT 7', 'BSW Hit 7'),
    ('BSW HIT 8', 'BSW Hit 8'),
    ('BSW HOUSE 1', 'BSW House 1'),
    ('BSW HOUSE 2', 'BSW House 2'),
    ('BSW HOUSE 3', 'BSW House 3'),
    ('BSW JAZZ 1', 'BSW Jazz 1'),
    ('BSW L&S', 'BSW L＆S'),
    ('BSW R&B 1', 'BSW R＆B 1'),
    ('BSW REGGAE 1', 'BSW Reggae 1'),
    ('BSW ROCK 1', 'BSW Rock 1'),
    ('BSW SOUL 1', 'BSW Soul 1'),
    ('BSWi HIPHOP 1', 'BSWi HipHop 1'),
    ('BSWi HOUSE 1', 'BSWi House 1'),
    ('BSWi HOUSE 2', 'BSWi House 2'),
    ('BSWi HOUSE 3', 'BSWi House 3'),
    ('BSWi HOUSE 4', 'BSWi House 4'),
    ('BSWi METAL 1', 'BSWi Metal 1'),
    ('10TH SP', '10th SP')
  ) AS t(old_name, new_name) LOOP
    IF EXISTS (SELECT 1 FROM programs WHERE program_name = r.new_name) THEN
      -- Target already exists (from scraper): copy series to existing entry, delete old
      UPDATE programs SET series = (SELECT series FROM programs WHERE program_name = r.old_name)
        WHERE program_name = r.new_name AND series IS NULL;
      DELETE FROM programs WHERE program_name = r.old_name;
    ELSE
      -- Simple rename
      UPDATE programs SET program_name = r.new_name WHERE program_name = r.old_name;
    END IF;
  END LOOP;
END $$;
